/**
 * @fileoverview Minifies the shipped JS and CSS in place, at Netlify build time.
 *
 * WHY THIS RUNS ON NETLIFY AND NEVER LOCALLY
 * The repository IS the deploy artifact: netlify.toml publishes "." after the
 * build command. Everything committed is readable, prettier-formatted source
 * -- main.js alone was 483 KB (136 KB gzip) on every page -- and it stays that
 * way, because every test in this repo runs against the source and
 * verify-build-reproducibility.js asserts that five rebuilds produce zero
 * diffs. So this script is the last step of the Netlify build command
 * (generated by build-security-headers.js), after build-site-data.js has
 * regenerated the data files and build-security-headers.js has rewritten the
 * headers. Its output is never committed. Run it by hand only on a copy of the
 * tree (scripts/minified-build.browser.test.js does exactly that).
 *
 * WHAT IT TOUCHES, AND WHAT IT MUST NOT
 *   - assets/js/*.js and assets/js/locales/*.js: minified with esbuild's
 *     transform API. No bundling, no renaming of files, no source maps.
 *   - assets/css/*.css: minified with esbuild's CSS minifier, with NO browser
 *     target, so native CSS nesting (`&:hover {}`) and `@container` stay
 *     exactly as written instead of being flattened for older engines.
 *   - sw.js is NEVER touched: the deploy check in AGENTS.md greps its
 *     CACHE_NAME line on the live site and compares it byte-for-byte to git.
 *   - HTML is NEVER touched: every inline <script> is pinned by a CSP hash
 *     (scripts/inline-script-hashes.json); rewriting a page would change a
 *     hash and the CSP would block the script.
 *   - assets/js/modules/ is left alone: no page references those files.
 *
 * File names are unchanged because sw.js precaches exact paths and the pages
 * reference `assets/js/x.js?v=2.0`. Only the bytes at each path shrink.
 *
 * WHY target es2020
 * The source already ships optional chaining (`?.`), nullish coalescing (`??`)
 * and optional catch binding unlowered, so the site's effective floor is
 * ES2020 today. es2020 is the lowest esbuild target whose output is
 * byte-identical to `esnext` for every file here (checked file by file on
 * 2026-09-09): nothing is lowered, nothing newer is introduced, and no
 * helper code is injected. A lower target would only rewrite `a?.b` into
 * ternaries -- larger output for a browser population that cannot run the
 * page anyway. `charset: "utf8"` keeps the CJK dictionaries as UTF-8 rather
 * than expanding every character into a `\uXXXX` escape.
 *
 * Idempotent: every file it writes ends with a marker comment, and a file that
 * already carries it is left byte-for-byte alone, so running twice (a Netlify
 * retry, a local experiment) is harmless. The marker, not esbuild, is what
 * guarantees that -- see minifyOne().
 *
 * Usage:
 *   node scripts/minify-assets.js            minify in place under the repo root
 *   node scripts/minify-assets.js --root DIR minify a copy of the tree at DIR
 */

const fs = require("fs");
const path = require("path");
const zlib = require("zlib");
const esbuild = require("esbuild");

const args = process.argv.slice(2);
const rootFlag = args.indexOf("--root");
const ROOT = rootFlag !== -1 ? path.resolve(args[rootFlag + 1]) : path.resolve(__dirname, "..");
/* In place, the repository is the deploy artifact and the tests read source:
   minified files must never land in a commit. Without `--root` this only runs
   where Netlify sets NETLIFY=true (its build image), so `npm run minify` on a
   developer machine stops here instead of rewriting the tree. */
if (rootFlag === -1 && process.env.NETLIFY !== "true") {
  console.error(
    "minify-assets: refusing to minify the repository in place. Pass --root <copy> " +
      "to minify a scratch copy; Netlify's build runs it with NETLIFY=true."
  );
  process.exit(2);
}

const JS_TARGET = "es2020";
const JS_DIRS = ["assets/js", "assets/js/locales"];
const CSS_DIRS = ["assets/css"];
/* Paths that must come out of this script byte-identical. sw.js is not under
   any of the directories above, but it is listed so a future re-organisation
   cannot pull it in silently. */
const NEVER_TOUCH = new Set(["sw.js"]);
/* Appended to every file this script writes. A file that already ends with
   it is skipped, which is what makes a second run a no-op. Exported for the
   browser suite, which asserts the served bytes carry it. */
const MARKER = "/*! minified by scripts/minify-assets.js */";
module.exports = { MARKER };

function listFiles(dir, ext) {
  const full = path.join(ROOT, dir);
  if (!fs.existsSync(full)) {
    throw new Error(`minify-assets: ${dir} does not exist under ${ROOT}`);
  }
  return fs
    .readdirSync(full)
    .filter((f) => f.endsWith(ext))
    .sort()
    .map((f) => path.join(dir, f))
    .filter((rel) => !NEVER_TOUCH.has(rel));
}

function gzipSize(buf) {
  return zlib.gzipSync(buf, { level: 9 }).length;
}

function kb(n) {
  return (n / 1024).toFixed(1).padStart(7) + " KB";
}

async function minifyOne(rel) {
  const abs = path.join(ROOT, rel);
  const before = fs.readFileSync(abs);
  const isCss = rel.endsWith(".css");
  const options = isCss
    ? { loader: "css", minify: true }
    : { loader: "js", minify: true, target: JS_TARGET, charset: "utf8" };
  /* Already minified by an earlier run (a Netlify retry, a second local pass
     over the same copy): leave the bytes exactly as they are. esbuild's output
     is NOT its own fixed point -- re-minifying main.js or cart.js flips between
     two equally short identifier assignments forever -- so idempotence comes
     from the trailing marker, not from esbuild. */
  if (before.toString("utf8").trimEnd().endsWith(MARKER)) {
    const gz = gzipSize(before);
    return { rel, rawBefore: before.length, rawAfter: before.length, gzBefore: gz, gzAfter: gz };
  }
  const result = await esbuild.transform(before.toString("utf8"), options);
  for (const w of result.warnings) {
    /* Warnings are reported, never fatal: esbuild emits the flagged rule as
       written, so the browser sees exactly what it saw before. */
    const where = w.location ? `:${w.location.line}` : "";
    console.warn(`  warning ${rel}${where}: ${w.text}`);
  }
  if (!result.code.trim()) {
    throw new Error(`minify-assets: ${rel} minified to an empty file -- refusing to write it`);
  }
  const after = Buffer.from(result.code.trimEnd() + "\n" + MARKER + "\n", "utf8");
  fs.writeFileSync(abs, after);
  return {
    rel,
    rawBefore: before.length,
    rawAfter: after.length,
    gzBefore: gzipSize(before),
    gzAfter: gzipSize(after)
  };
}

async function main() {
  const files = []
    .concat(...JS_DIRS.map((d) => listFiles(d, ".js")))
    .concat(...CSS_DIRS.map((d) => listFiles(d, ".css")));
  if (!files.length) throw new Error("minify-assets: found nothing to minify");

  // Every HTML page at every depth the build emits: top level, products/, journal/.
  const html = [""].concat(["products", "journal"]).flatMap((dir) => {
    const abs = path.join(ROOT, dir);
    if (!fs.existsSync(abs)) return [];
    return fs
      .readdirSync(abs)
      .filter((f) => f.endsWith(".html"))
      .map((f) => (dir ? path.join(dir, f) : f));
  });
  const htmlBefore = fingerprint(html);
  const swBefore = fs.existsSync(path.join(ROOT, "sw.js"))
    ? fs.readFileSync(path.join(ROOT, "sw.js"))
    : null;

  console.log(`minify-assets: ${files.length} files under ${ROOT} (JS target ${JS_TARGET})\n`);
  console.log(
    "  " +
      "file".padEnd(34) +
      "raw before".padStart(11) +
      "raw after".padStart(11) +
      "gzip before".padStart(13) +
      "gzip after".padStart(12)
  );
  const rows = [];
  for (const rel of files) {
    const row = await minifyOne(rel);
    rows.push(row);
    console.log(
      "  " +
        rel.padEnd(34) +
        kb(row.rawBefore) +
        kb(row.rawAfter) +
        "  " +
        kb(row.gzBefore) +
        kb(row.gzAfter)
    );
  }
  const sum = (k) => rows.reduce((n, r) => n + r[k], 0);
  console.log(
    "  " +
      "total".padEnd(34) +
      kb(sum("rawBefore")) +
      kb(sum("rawAfter")) +
      "  " +
      kb(sum("gzBefore")) +
      kb(sum("gzAfter"))
  );

  /* Self-check: the two things this script promises never to change. */
  if (swBefore && !swBefore.equals(fs.readFileSync(path.join(ROOT, "sw.js")))) {
    throw new Error("minify-assets: sw.js changed -- it must never be rewritten");
  }
  if (!html.length || fingerprint(html) !== htmlBefore) {
    throw new Error("minify-assets: a top-level HTML page changed -- CSP hashes would break");
  }
  console.log(`\n  sw.js untouched; ${html.length} HTML pages untouched.`);
}

function fingerprint(relPaths) {
  const hash = require("crypto").createHash("sha256");
  for (const rel of relPaths) hash.update(fs.readFileSync(path.join(ROOT, rel)));
  return hash.digest("hex");
}

/* Runs only as a CLI. Requiring the module (the browser suite does, for
   MARKER) must not minify anything. */
if (require.main === module) {
  main().catch((err) => {
    console.error(err && err.stack ? err.stack : String(err));
    process.exit(1);
  });
}
