#!/usr/bin/env node
"use strict";

/* ==========================================================
   Y'ALLTERNATIVE LIVING -- responsive AVIF+WebP image pipeline
   ----------------------------------------------------------
   Generates small/medium/full AVIF *and* WebP variants for every
   product photo in assets/img/, then writes
   assets/js/image-manifest.js so the site's <picture> markup always
   knows exactly which variants exist and how wide each one is.

   AVIF goes first in the <picture> markup (main.js) because it's
   the better-compressing modern format (2026 browser support is
   effectively universal on anything that isn't ancient); WebP is
   the fallback for the rare holdout, and the original JPG is the
   final safety net for anything that supports neither.

   Run this any time a new product photo gets dropped into
   assets/img/ -- HOW TO ADD A NEW PRODUCT PHOTO:
     1. Drop the new .jpg into assets/img/
     2. Reference it from assets/js/products-data.js as usual
     3. Run: node scripts/optimize-images.js
        (or: npm run optimize-images)
   That regenerates both formats' variants and the manifest so the
   new photo gets the same fast, responsive treatment automatically
   -- nobody has to remember a manual conversion step.

   This is a dev-time build tool only. Requires the "sharp"
   devDependency (see package.json). The deployed site itself
   stays 100% static HTML/CSS/JS -- sharp never ships, it just
   pre-generates files that get committed/deployed alongside
   everything else.
   ========================================================== */

var fs = require("fs");
var path = require("path");
var sharp = require("sharp");

var ROOT = path.join(__dirname, "..");
var IMG_DIR = path.join(ROOT, "assets", "img");
var MANIFEST_PATH = path.join(ROOT, "assets", "js", "image-manifest.js");

var WIDTHS = [480, 800]; // plus one "full" variant at the source's own width
var WEBP_QUALITY = 80;
// AVIF's compression curve isn't the same as WebP's -- a lower quality
// number here looks comparable to WEBP_QUALITY=80 while encoding
// smaller, which is the whole point of adding it.
var AVIF_QUALITY = 55;
// libaom's default encode effort (4) is noticeably slower per image than
// WebP for a real gain of only a few percent smaller files -- effort 2
// keeps AVIF's size advantage over WebP while running several times
// faster, which matters when re-encoding dozens of photos at once.
var AVIF_EFFORT = 2;

// Small/UI images that don't need the responsive treatment --
// they're already tiny and used at a fixed, small size everywhere.
var SKIP_EXACT = ["logo.jpg", "logo.png"];

function shouldSkip(filename) {
  if (SKIP_EXACT.indexOf(filename) !== -1) return true;
  if (/^favicon/i.test(filename)) return true;
  return false;
}

async function optimizeOne(filename) {
  var base = filename.replace(/\.(jpe?g|png)$/i, "");
  var srcPath = path.join(IMG_DIR, filename);
  var meta = await sharp(srcPath).metadata();
  var srcWidth = meta.width || 1200;
  var srcHeight = meta.height || Math.round(srcWidth * 0.85);

  var avifVariants = [];
  var webpVariants = [];

  for (var i = 0; i < WIDTHS.length; i++) {
    var w = WIDTHS[i];
    if (w >= srcWidth) continue; // never upscale

    var webpOut = base + "-" + w + ".webp";
    await sharp(srcPath)
      .resize({ width: w })
      .webp({ quality: WEBP_QUALITY })
      .toFile(path.join(IMG_DIR, webpOut));
    webpVariants.push({ width: w, file: "assets/img/" + webpOut });

    var avifOut = base + "-" + w + ".avif";
    await sharp(srcPath)
      .resize({ width: w })
      .avif({ quality: AVIF_QUALITY, effort: AVIF_EFFORT })
      .toFile(path.join(IMG_DIR, avifOut));
    avifVariants.push({ width: w, file: "assets/img/" + avifOut });
  }

  // Full-size variants, always included, always the widest -- this is
  // what large screens / the srcset's biggest candidate use.
  var fullWebp = base + ".webp";
  await sharp(srcPath).webp({ quality: WEBP_QUALITY }).toFile(path.join(IMG_DIR, fullWebp));
  webpVariants.push({ width: srcWidth, file: "assets/img/" + fullWebp });

  var fullAvif = base + ".avif";
  await sharp(srcPath)
    .avif({ quality: AVIF_QUALITY, effort: AVIF_EFFORT })
    .toFile(path.join(IMG_DIR, fullAvif));
  avifVariants.push({ width: srcWidth, file: "assets/img/" + fullAvif });

  var beforeSize = fs.statSync(srcPath).size;
  return {
    key: "assets/img/" + filename,
    width: srcWidth,
    height: srcHeight,
    size: beforeSize,
    variants: { avif: avifVariants, webp: webpVariants }
  };
}

function writeManifest(manifest) {
  var header =
    "/* AUTO-GENERATED by scripts/optimize-images.js -- do not hand-edit.\n" +
    "   Maps each original product photo to its responsive AVIF + WebP\n" +
    "   variants so main.js can build <picture> markup without guessing\n" +
    "   which files exist. Re-run the script any time a product photo\n" +
    "   changes or a new one gets added. */\n";
  var body = "window.YL_IMAGES = " + JSON.stringify(manifest, null, 2) + ";\n";
  var dir = path.dirname(MANIFEST_PATH);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.writeFileSync(MANIFEST_PATH, header + body);
}

function loadExistingManifest() {
  if (!fs.existsSync(MANIFEST_PATH)) return {};
  try {
    var stub = {};
    // `window` below is used inside the eval()'d manifest text
    // ("window.YL_IMAGES = ..."), not visible to static analysis, so it
    // looks unused from the linter's view -- it isn't.
    // eslint-disable-next-line no-unused-vars
    (function (window) {
      eval(fs.readFileSync(MANIFEST_PATH, "utf8"));
    }).call(null, stub);
    return stub.YL_IMAGES || {};
  } catch (e) {
    return {};
  }
}

async function run() {
  if (!fs.existsSync(IMG_DIR)) {
    console.log("Creating missing image directory: " + IMG_DIR);
    fs.mkdirSync(IMG_DIR, { recursive: true });
  }
  var files = fs
    .readdirSync(IMG_DIR)
    .filter(function (f) {
      return /\.(jpe?g|png)$/i.test(f) && !shouldSkip(f);
    })
    .sort();

  if (!files.length) {
    console.log("No .jpg product photos found in assets/img/ -- nothing to do.");
    return;
  }

  // Optional: `node scripts/optimize-images.js tank-top,unisex-tshirt`
  // restricts this run to just those base filenames (no extension) --
  // encoding AVIF at real quality is slow enough that doing all 40+
  // photos in one process can take longer than is comfortable in a
  // single terminal session, so batching a few at a time is supported.
  // Every run merges into whatever manifest already exists (and writes
  // it after EACH photo, not just at the end) so a batch that gets
  // interrupted partway never loses previously-finished work.
  var force = process.argv.indexOf("--force") !== -1 || process.argv.indexOf("-f") !== -1;
  var args = process.argv.slice(2).filter(function (arg) {
    return !arg.startsWith("-");
  });
  var onlyArg = args.join(",");
  if (onlyArg) {
    var wanted = onlyArg.split(",").map(function (s) {
      return s.trim();
    });
    files = files.filter(function (f) {
      var base = f.replace(/\.(jpe?g|png)$/i, "");
      return wanted.indexOf(base) !== -1;
    });
    if (!files.length) {
      console.log("No matching files for: " + onlyArg);
      return;
    }
  }

  var manifest = loadExistingManifest();
  var beforeTotal = 0;
  var avifSmallestTotal = 0; // what an AVIF-capable phone actually downloads
  var avifFullTotal = 0; // what an AVIF-capable desktop actually downloads
  var webpSmallestTotal = 0; // same, for the WebP fallback path

  for (var i = 0; i < files.length; i++) {
    var filename = files[i];
    var fullPath = path.join(IMG_DIR, filename);
    var currentSize = fs.statSync(fullPath).size;
    var entry = manifest["assets/img/" + filename];

    if (!force && entry && entry.size === currentSize && entry.variants) {
      // Check if all variant files actually exist on disk
      var allExist = true;
      var checkVariant = function (v) {
        if (!fs.existsSync(path.join(ROOT, v.file))) allExist = false;
      };
      entry.variants.avif.forEach(checkVariant);
      entry.variants.webp.forEach(checkVariant);

      if (allExist) {
        console.log(filename + " is already optimized. Skipping.");
        var beforeSize = entry.size || currentSize;
        beforeTotal += beforeSize;
        var avifSizes = entry.variants.avif.map(function (v) {
          return fs.existsSync(path.join(ROOT, v.file)) ? fs.statSync(path.join(ROOT, v.file)).size : 0;
        });
        var webpSizes = entry.variants.webp.map(function (v) {
          return fs.existsSync(path.join(ROOT, v.file)) ? fs.statSync(path.join(ROOT, v.file)).size : 0;
        });
        avifSmallestTotal += Math.min.apply(null, avifSizes);
        avifFullTotal += avifSizes[avifSizes.length - 1];
        webpSmallestTotal += Math.min.apply(null, webpSizes);
        continue;
      }
    }

    entry = await optimizeOne(filename);
    manifest[entry.key] = entry;
    writeManifest(manifest); // persist after every photo, not just at the end

    var beforeSize = entry.size || currentSize;
    beforeTotal += beforeSize;

    var avifSizes = entry.variants.avif.map(function (v) {
      return fs.statSync(path.join(ROOT, v.file)).size;
    });
    var webpSizes = entry.variants.webp.map(function (v) {
      return fs.statSync(path.join(ROOT, v.file)).size;
    });
    avifSmallestTotal += Math.min.apply(null, avifSizes);
    avifFullTotal += avifSizes[avifSizes.length - 1];
    webpSmallestTotal += Math.min.apply(null, webpSizes);

    console.log(
      filename +
        ": " +
        Math.round(beforeSize / 1024) +
        "KB jpg -> " +
        "avif[" +
        entry.variants.avif
          .map(function (v, idx) {
            return v.width + "w " + Math.round(avifSizes[idx] / 1024) + "KB";
          })
          .join(", ") +
        "] " +
        "webp[" +
        entry.variants.webp
          .map(function (v, idx) {
            return v.width + "w " + Math.round(webpSizes[idx] / 1024) + "KB";
          })
          .join(", ") +
        "]"
    );
  }

  console.log("");
  console.log("wrote assets/js/image-manifest.js (" + files.length + " photos)");
  console.log(
    "A browser only ever downloads ONE variant per image (whichever format+\n" +
      "size its <picture> pick lands on), never all of them -- so the real\n" +
      "comparison is against the single original JPG each replaces:"
  );
  console.log(
    "  Phones, AVIF-capable (~96%+ of traffic in 2026): " +
      Math.round(beforeTotal / 1024) +
      "KB -> " +
      Math.round(avifSmallestTotal / 1024) +
      "KB (" +
      Math.round((1 - avifSmallestTotal / beforeTotal) * 100) +
      "% smaller)"
  );
  console.log(
    "  Desktop, AVIF-capable, full size:                 " +
      Math.round(beforeTotal / 1024) +
      "KB -> " +
      Math.round(avifFullTotal / 1024) +
      "KB (" +
      Math.round((1 - avifFullTotal / beforeTotal) * 100) +
      "% smaller)"
  );
  console.log(
    "  Phones, WebP fallback (no AVIF support):          " +
      Math.round(beforeTotal / 1024) +
      "KB -> " +
      Math.round(webpSmallestTotal / 1024) +
      "KB (" +
      Math.round((1 - webpSmallestTotal / beforeTotal) * 100) +
      "% smaller)"
  );
}

run().catch(function (err) {
  console.error(err);
  process.exit(1);
});
